docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="dump_data" \
  -v C:/Hamed Files/data_engineering/02-postgres/postgres_config:/var/lib/postgres/data \
  -p 5432:5432 \
  postgres:13